# ===========================
# Model Selection
# ===========================
model_name: lstm_classifier

# ===========================
# Model Parameters
# ===========================
input_size: 48
hidden_size: 128
num_layers: 2
bidirectional: false
dropout: 0.1

# ===========================
# Output & Artifacts
# ===========================
model_directory: models
models_out_path: <your_models_output_path>
outputs_dir: <your_outputs_path>
